### ISSUE TITLE
VSS 3.4.0 not respecting backup timer

### ISSUE THREAD

**Issue by chimi420** [Razzmatazzz/ValheimSaveShield#13]
I updated from 3.3.0 and had a 10 minute between backup set.  Now it is backing up every 20 minutes despite what I put into the field.  Is there a Save button I'm overlooking?

**Comment by Razzmatazzz** [comment]
As explained [here](https://github.com/Razzmatazzz/ValheimSaveShield/wiki), the game only saves every 20 minutes, so there's nothing to backup in the interim.
