### ISSUE TITLE
Misplaced "return;" statement.

### ISSUE THREAD

**Issue by Polomease** [Razzmatazzz/ValheimSaveShield#15]
https://github.com/Razzmatazzz/ValheimSaveShield/blob/f22ede3499d4a4d02eab912184fd75fa6bd79fff/MainWindow.xaml.cs#L978

This return; statement is causing the function to exit without updating the backup folder. I assume it's supposed to be in the IF block that's before it.

**Comment by Razzmatazzz** [comment]
Thanks for the report and pinpoint diagnosis. Just put out an updated release that fixes it.
