### ISSUE TITLE
Backup additional files in server save folder?

### ISSUE THREAD

**Issue by Fing3rz** [Razzmatazzz/ValheimSaveShield#17]
I am using a mod called Server Side Map and it creates seperate explored map file in the save folder that it syncs to clients when they connect. I suspect it or additional mods will add extra files in the future. Would like to see an option to backup those files. Thanks

**Comment by Razzmatazzz** [comment]
Adding the ability to back up any and all additional files that mods might introduce into the save folder might be a bit outside the scope of this little app. I can't currently envision a way to handle this kind of thing that wouldn't significantly complicate most other parts of the app.

Does the map happen to be named something like WorldName.mapfileextension?

**Comment by Fing3rz** [comment]
RAGNAROK.mod.serversidemap.explored
RAGNAROK being the worldname

**Comment by Fing3rz** [comment]
yes

**Comment by Razzmatazzz** [comment]
[vss-test-2021-03-01 01.zip](https://github.com/Razzmatazzz/ValheimSaveShield/files/6063512/vss-test-2021-03-01.01.zip)
Give this test version a try. I think it does what you need it to. Click the "Extra world files" button in the Settings tab to add additional file extensions for backing up.

**Comment by Fing3rz** [comment]
works great! just added .mod.serversidemap.explored to the list and it backed it up just fine. Thanks

**Comment by Razzmatazzz** [comment]
Implemented in latest release.
