### ISSUE TITLE
Automatic backup interval cannot be changed

### ISSUE THREAD

**Issue by IndecisiveGoliath** [Razzmatazzz/ValheimSaveShield#18]
I have had this problem since the first version of this program. I set my "minutes between backups" to five minutes. It seems to only backup every 20 minutes regardless of what I put in the window. If we had a way of saving our setting it may help. However I do not code so I have no idea how difficult it is. Thanks!

**Comment by Razzmatazzz** [comment]
As explained [here](https://github.com/Razzmatazzz/ValheimSaveShield/wiki), the game only saves every 20 minutes, so there's nothing new to back up before a new save is made.
