### ISSUE TITLE
World isn't getting auto backed up

### ISSUE THREAD

**Issue by Flipnotix** [Razzmatazzz/ValheimSaveShield#20]
I noticed my world that I am hosting doesn't get backed up. I don't think it ever has since like 4 versions ago. I am hosting it using steamcmd method and I'm using Version 0.4.3.0. The save path(C:\Users\MyUser\AppData\LocalLow\IronGate\Valheim) is correct since it detects my character fine, but my world is under the same folder in "worlds". My log file mentions nothing about my world.

**Comment by Razzmatazzz** [comment]
Please post the config file you're using for the server (password removed, of course).

**Comment by Flipnotix** [comment]
:start
C:\Users\My User\Desktop\steamcmd\steamcmd.exe +login anonymous +force_install_dir C:\Users\My User\Desktop\steamcmd\valheim +app_update 896660 +quit
:juststart
@echo off
set SteamAppId=892970

echo "Starting server PRESS CTRL-C to exit"

REM Tip: Make a local copy of this script to avoid it being overwritten by steam.
REM NOTE: Minimum password length is 5 characters & Password cant be in the server name.
REM NOTE: You need to make sure the ports 2456-2458 is being forwarded to your server through your local router & firewall.
valheim_server -nographics -batchmode -name "Cannibal Coop" -port 2456 -world "ForestFriends" -password ""

This file? This is what I run to start the server.

**Comment by Razzmatazzz** [comment]
I'm at a loss here. The character and world should be in the same save location. The app uses the exact same logic for detecting world and character save updates. The app has been happily backing up my own dedicated world save without any issues. I'm not seeing anything that could cause it to not work.

**Comment by cproxy** [comment]
Sorry to say, I just moved my server to another machine and set this up, doesn't detect saves.  I've tried several levels of directories.



[ValheimSaveShield.zip](https://github.com/Razzmatazzz/ValheimSaveShield/files/6093106/ValheimSaveShield.zip)

**Comment by Razzmatazzz** [comment]
@cproxy Is it the FTP feature you're having no success with?

**Comment by cproxy** [comment]
@Razzmatazzz no, and I saw those log files too.  Here is the GUI.
![image](https://user-images.githubusercontent.com/44812073/110670556-5fec8600-8182-11eb-9e09-917fa2d54c33.png)
![image](https://user-images.githubusercontent.com/44812073/110670646-798dcd80-8182-11eb-8c05-0337db499f74.png)

**Comment by Razzmatazzz** [comment]
@cproxy Which is the folder containing your Worldname.db and Worldname.fwl files?

**Comment by cproxy** [comment]
C:\Users\Public\World\worlds

I was just trying anything in the screenshot above.

I upgraded to 0.4.8.0 and switch it back to C:\Users\Public\World\worlds

![image](https://user-images.githubusercontent.com/44812073/110691048-7d791a00-8199-11eb-8273-bbc8ab7321f7.png)

**Comment by Razzmatazzz** [comment]
You should set your save folder to C:\Users\Public\World

**Comment by cproxy** [comment]
> You should set your save folder to C:\Users\Public\World

Done.  Still no love, sadly. 

Thought for the first time, the little status icon says "not backed up"

Logs don't say why though.  Is there debug logging I can turn on?

Wm

**Comment by cproxy** [comment]
> You should set your save folder to C:\Users\Public\World

I swear I did, but I guess that was it...  I was able to manually save.  I'll wait for the automatic save to fire and confirm.

Thanks!

**Comment by Razzmatazzz** [comment]
Glad to hear you got it working.

**Comment by Razzmatazzz** [comment]
@Flipnotix Trying to get your issue resolved, can you please confirm the following:

- You have ForestFriends.db and ForestFriends.fwl files in your %userprofile%/appdata/locallow/irongate/valheim/worlds folder
- These files show "last modified" dates/times of no more than 20 minutes ago (assuming your dedicated server is still running)
- VSS shows the status of all saves being backed up, but only displays character backups and has no backups for ForestFriends

**Comment by Flipnotix** [comment]
Sorry for the late response.
![val](https://user-images.githubusercontent.com/80001317/111150907-eec71d00-854b-11eb-8624-675ff87c063a.png)
My dedicated server is no longer running, but it decided to save once when I manually backed up my character. Since the server files haven't been updated, it hasn't auto backed up.
VSS log did show my character getting backed up, but no mention of the world file besides the time I created a manual backup.

**Comment by Razzmatazzz** [comment]
Have you been playing singleplayer using that world? If so, it should be auto backing up. If you haven't been playing using that world, then the save file isn't changing and there's nothing for VSS to back up.

**Comment by Flipnotix** [comment]
I tested on singleplayer mode with the newest version, and it didn't auto backup every 10 mins like I set it to. It did finally save my world when I exited singleplayer mode and hit manual backup button. I will test it on my dedicated server when I have time and get back to you.

**Comment by Razzmatazzz** [comment]
[The game does not save more frequently than 20 minutes, so there is nothing new to backup in the interim.](https://github.com/Razzmatazzz/ValheimSaveShield/issues/19)

**Comment by Razzmatazzz** [comment]
@Flipnotix Are things working as expected for you? If so, I'd like to close this issue.

**Comment by Flipnotix** [comment]
I tested in singleplayer and waited out the 20 minutes, and both files saved. I haven't had the time to really play and test on my dedicated server. My issue is probably resolved now thank you.

**Comment by Razzmatazzz** [comment]
Great, good to hear. Please open up another issue if you experience further problems.
