### ISSUE TITLE
0.4.3.0 Not keeping "Keep" check marks

### ISSUE THREAD

**Issue by tgoVIPER** [Razzmatazzz/ValheimSaveShield#21]
I'm trying to "Keep" a couple worlds and a character.
If I've checked "Keep" on the ones I want, when I close and re-open the program, the checks are no longer there.

**Comment by Razzmatazzz** [comment]
Indeed; the IDE undid some of my changes so they weren't being properly saved. Fixed now. Thanks for reporting.
