### ISSUE TITLE
Program Not Seeing World

### ISSUE THREAD

**Issue by throoper** [Razzmatazzz/ValheimSaveShield#22]
I run a dedicated server and play on the same pc. My game files were placed in a root folder on my C drive called "Worlds". Inside that folder are both character and worlds folders. I directed VSS to top level "Worlds" folder but my world does not appear in the backups list. Any assistance or thoughts on what could be going wrong would be appreciated!

**Comment by Razzmatazzz** [comment]
Just to make sure we're on the same page, my understanding is:

- You've confirmed there are world files saved in your C:\Worlds\worlds folder
- You've added C:\Worlds as a save folder to monitor in VSS
- When you launch VSS, it doesn't display any backups of your server world, and it says all saves are backed up

Is that all correct?

**Comment by Razzmatazzz** [comment]
@throoper I'm happy to help you troubleshoot this, but if I don't hear back from you by 3/12, I'll be closing this issue.

**Comment by Razzmatazzz** [comment]
Closing this issue for lack of clarification. We can troubleshoot if you provide some more details.
