### ISSUE TITLE
discord notification issue

### ISSUE THREAD

**Issue by SkOODaT** [Razzmatazzz/ValheimSaveShield#23]
Server {Server.Name} failed to start. uses Server {Server.Name} has started. instead needs a simple bugfix~ no one has noticed lol

**Comment by Razzmatazzz** [comment]
I'm not sure I understand; for me the default message for the server failing to start is "Server {Server.Name} failed to start."

**Comment by SkOODaT** [comment]
hit "test" on server failed to start ... it will fire off server started ~

**Comment by Razzmatazzz** [comment]
Oh yeah, I see now. Thanks.
