### ISSUE TITLE
Prevent multiple instances of program starting

### ISSUE THREAD

**Issue by sylvank** [Razzmatazzz/ValheimSaveShield#27]
With the app minimizing to the tray, it might not be obvious if it's running or not. Double-clicking the app icon a second time launches a second instance of the program. I believe it's possible when this happens for the new instance to identify the primary instance, bring it to the front, and terminate its own process, which would be a more user-friendly result.

**Comment by Razzmatazzz** [comment]
I can look into implementing something like this.

**Comment by Razzmatazzz** [comment]
This is in the latest release. Thanks for the suggestion.

**Comment by sylvank** [comment]
Awesome, thanks!
