### ISSUE TITLE
need to be able to open 2 instances

### ISSUE THREAD

**Issue by SkOODaT** [Razzmatazzz/ValheimSaveShield#28]
im running 2 diff dedicated server folders and 2 different worlds, can you add an option to allow 2 instances or more same time, i kno0w the risks if their both in the same directory lol

**Comment by Razzmatazzz** [comment]
Why not just add the additional servers' folders as additional save folders [as documented in the wiki](https://github.com/Razzmatazzz/ValheimSaveShield/wiki)? There's no need to run multiple instances.

**Comment by SkOODaT** [comment]
damn i never even saw that option ... ive been running 2 lol hidden option :P

**Comment by Razzmatazzz** [comment]
Yeah, it's not super-prominent since I wanted it to basically be transparent for anyone just running a normal game without a dedicated server. So I guess it's maybe achieving that design goal just a little too well!
