### ISSUE TITLE
dont save and getting error

### ISSUE THREAD

**Issue by robzera** [Razzmatazzz/ValheimSaveShield#29]
System.IO.DirectoryNotFoundExeption processsing save file change: in Sistem.IO._Error(int32 errorCode, String maybefullpath

this error
log:
18/03/2021 20:36:03: System.IO.DirectoryNotFoundException processing save file change: Não foi possível localizar uma parte do caminho 'C:\Users\robpica\AppData\LocalLow\IronGate\Valheim\backups\worlds\CAETANOCORNO'. (   em System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   em System.IO.FileSystemEnumerableIterator`1.CommonInit()
   em System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   em System.IO.Directory.GetDirectories(String path)
   em ValheimSaveShield.SaveFile.get_BackupDueTime()
   em ValheimSaveShield.SaveFile.get_NeedsBackedUp()
   em ValheimSaveShield.MainWindow.OnSaveTimerElapsed(Object source, ElapsedEventArgs e))
18/03/2021 20:35:57: Version 0.4.9.0

**Comment by Razzmatazzz** [comment]
It sounds like VSS is unable to create the "CAETANOCORNO" to back up your world of that same name. Please do the following:

- Go the Settings tab of VSS
- Right-click the Save Folder path and then click Open in Windows Explorer
- Open the worlds folder
- Copy the exact name of the World.db file that corresponds with "CAETANOCORNO". There might be extra spaces or something in the filename. Paste the filename here.
- Back in VSS, right-click the Backup Folder path and then click Open in Windows Explorer
- Open the worlds folder
- Is there a folder there that corresponds with "CAETANOCORNO" but is slightly different in some way?

**Comment by robzera** [comment]
you are really very fast omg, you really solved my problem, do you think about making a video on youtube for that? can I make a video about your program for my audience from Brazil?

**Comment by Razzmatazzz** [comment]
I'm honestly not sure what I solved; I was just trying to collect information to diagnose your problem. What fixed the problem for you?
