### ISSUE TITLE
FTP & normal backups timing issue

### ISSUE THREAD

**Issue by Valdaun** [Razzmatazzz/ValheimSaveShield#30]
I have just started using VSS to backup an FTP server which is really cool!  However, because everything happens at the same schedule, while the files itself from the FTP are successfully backed up into the normal game Worlds local folder, the local backup immediately also runs and that 95%+ of the time fails to get a full copy of the .db file (because it is only partially downloaded at the time the local copy kicks off).    If the jobs were simply separated by 50% of the time between checks I think that would be a sensible solution.   So, if I have it set every 10 minutes, then at minute 0, local backup happens, minute 5 the FTP job happens, minute 10 the local happens again, etc.   That should give plenty of time to download from FTP even a large world and then make sure you actually can get successful historical backups of those FTP copies.  As is, I'm only getting 1 usable copy, the one in the worlds folder.   Thanks for this great program overall, has been a huge help for us in enjoying Valheim without worry that we will lose our hard work! :)

**Comment by Razzmatazzz** [comment]
Thanks for reporting this issue. Although the problem you're describing doesn't have anything to do with a backup "schedule." The app monitors the save folder for save file changes. When a change is detected, the app makes a backup if it's been X number of minutes since the most recent backup of that save.

I think what's happening is the start of the download triggers the save file change event but the file doesn't finish downloading before the backup is attempted. I tested this feature on my local LAN, so it didn't take a significant amount of time to complete downloads and this issue didn't present itself.

I'll have to give some thought as to the best way to handle this. How large (in MB) is the world.db file you're transferring via FTP?

**Comment by Razzmatazzz** [comment]
[vss-ftp-test.zip](https://github.com/Razzmatazzz/ValheimSaveShield/files/6177630/vss-ftp-test.zip)
Please try this test build to see if it solves the problem you've been experiencing.

**Comment by Valdaun** [comment]
Ah yeah that makes sense.   We've just gotten started and the world file is
30MB and growing, so it does take at least several seconds to copy down
from the Internet.  Would be good to either add a delay or otherwise try
and wait for the file to finish, but I'm sure that's easier said than done.
:)

**Comment by Razzmatazzz** [comment]
The .zip file I linked in my previous response contains a test version of the app that should fix your issue. Please let me know if that's not the case.

**Comment by Valdaun** [comment]
maybe another way to do the FTP would just be to allow to specify a
different target local folder for FTP backups, and to then do FTP on a
schedule every X minutes and maintain a rotation of X number of stored
backups in that alternate folder.   That's how I initially assumed it would
work, but it looks like you can't change the local save folder for FTP
backups as of now.

**Comment by Razzmatazzz** [comment]
**I INCLUDED A LINK TO A TEST VERSION THAT I BELIEVE FIXES THIS ISSUE. PLEASE TEST THAT VERSION AND LET ME KNOW IF IT FIXES THE ISSUE FOR YOU.**

You can specify a different local folder for your FTP saves.
- Right-click the save folder path
- Click Add save folder
- Select the folder where you want to keep your FTP saves
- Click the FTP Import button
- Select the save folder you just selected as the Local Save Folder Destination

**Comment by Valdaun** [comment]
Sorry, I hadn't gone back to the site in a bit so was just sending random thoughts on email lol    Thanks for the fast response, I will give this a shot and report back tomorrow!

**Comment by Valdaun** [comment]
FYI, this new version does kind of work better, but there is an issue with time stamps / TimeZone which is preventing the ability to see for sure if it is fixed.    The picture attached tries to explain fully, but basically when the files are downloaded with FTP via VSS, the time stamps are always in the future by 4 hours, which ends up preventing the logic that tries to keep a version history (last 10).
![VSS_FTP_TimeIssue](https://user-images.githubusercontent.com/8713530/111934777-7951d400-8a98-11eb-8dc2-3005bd6f1a7f.png)

**Comment by Valdaun** [comment]
I've left this running last night & this morning and while the time stamp issue is still a major factor, there were 3 times the stars aligned and a version copy was created.   Those 3 files all seem to be full size, so I think the original bug you were trying to fix did work. :)    If you can sort the time stamp issue, I would guess this will be good to go!

**Comment by Razzmatazzz** [comment]
[vss-test.zip](https://github.com/Razzmatazzz/ValheimSaveShield/files/6183315/vss-test.zip)
This test build will hopefully fix the differing time zone issue.

**Comment by Valdaun** [comment]
No worries!  I didn't expect such a fast response and figured you were still in "mulling it over" phase. :)    At any rate, I've let VSS run all day today with the version you posted and it seems to be working great!   I've carefully watched whenever I could, and the file sizes of the versioned FTP copies have always looked full size and match exactly to the single version in the FTP backup location.   The time stamps in windows are still not showing correctly (they are 4 hours ahead in my case, so still in the future), but that is not causing the versioning routine to fail so it's all good from my point of view.   I would say my 2 issues are resolved!

**Comment by Razzmatazzz** [comment]
Great, thanks for reporting and your help in diagnosing the issue.
