### ISSUE TITLE
Clicking "create log file" crashes the app

### ISSUE THREAD

**Issue by jeffersonswine** [Razzmatazzz/ValheimSaveShield#32]
Clicking "create log file" crashes the app
v0.4.10.0

**Comment by Razzmatazzz** [comment]
Strange; it doesn't crash the app for me. Is the vsw exe located somewhere that might require special permissions to create a file in the same folder?

**Comment by jeffersonswine** [comment]
exe is on my D drive.... I run programs on solid state C and all the data files on D
I'm the admin on the box, no special permissions for that folder or drive

**Comment by Razzmatazzz** [comment]
[vss-test.zip](https://github.com/Razzmatazzz/ValheimSaveShield/files/6215727/vss-test.zip)
To help troubleshoot, please use this test version. Instead of crashing it should display an error when you try to change that option. Let me know what the error is.

**Comment by jeffersonswine** [comment]
That test version works fine.  No problems.  Created the log file.
[log.txt](https://github.com/Razzmatazzz/ValheimSaveShield/files/6216139/log.txt)
