### ISSUE TITLE
Doesn't keep size of window 

### ISSUE THREAD

**Issue by Geksli** [Razzmatazzz/ValheimSaveShield#34]
i have 3440x1440 resolution (Ultrawide) 21:9 
at start, when you open program first time, she doesn't keep size of window 
idk but this is annoying, change size everytime

screen [https://cdn-104.anonfiles.com/JcH4y6x4u3/4ac17ee3-1621658646/screen.png](url)

**Comment by Razzmatazzz** [comment]
You should be able to resize the window, and the window should save its size when the app is closed.

If you haven't closed the app but instead ended the process or something, then it didn't have the opportunity to save the window size.

**Comment by Geksli** [comment]
> You should be able to resize the window, and the window should save its size when the app is closed.
> 
> If you haven't closed the app but instead ended the process or something, then it didn't have the opportunity to save the window size.

**Comment by Razzmatazzz** [comment]
So your system is rebooting while the app is running? If that's the case, the app probably isn't shutting down gracefully and the window dimensions aren't being saved.

**Comment by Geksli** [comment]
it turned out to be true, but it is not convenient. 

I have a bunch of programs in my system tray and I don't manually close them all before shutting down. it's very strange nowadays. i think you do not shutting all of your programs manually too.

**Comment by Razzmatazzz** [comment]
The solution is simple:

1. Launch the app.
2. Resize the app how you want it.
3. Manually close the app (this saving your preferred size)

Now anytime the app is opened, it will be your preferred size.

**Comment by Geksli** [comment]
Ok thx
Try it
