### ISSUE TITLE
FTP Support for Dedicated Servers

### ISSUE THREAD

**Issue by philip06** [Razzmatazzz/ValheimSaveShield#4]
It would be useful to integrate the auto-backup system with an ftp endpoint for Valheim servers hosted in the cloud.

**Comment by Razzmatazzz** [comment]
Not possible. This app monitors changes on a local file system and then performs a backup when changes are detected. There's no equivalent way to monitor for changes on a server hosted in the cloud.

**Comment by philip06** [comment]
I think I found a way to do it. Take a look at my pull request.

**Comment by Razzmatazzz** [comment]
Merged and included in latest release. Thanks for the contribution!
