### ISSUE TITLE
Application crashed and was removed from PC

### ISSUE THREAD

**Issue by langstonts** [Razzmatazzz/ValheimSaveShield#6]
Yesterday I setup and began running a dedicated server on my PC. This morning I restarted the server and started the backup application and left it running. Came back at the end of the day and it appears the application had crashed. Not completely odd but when I went to restart the application the exe file was missing. It appears that it's been completely removed from my device. Is it possible Windows Defender removed it?

**Comment by langstonts** [comment]
Update on this. Windows flagged the program as a trojan and removed it

**Comment by Razzmatazzz** [comment]
Yes, false positives are a regular annoyance. [See this issue for more info](https://github.com/Razzmatazzz/ValheimSaveShield/issues/1).
