### ISSUE TITLE
UI Tooltip showing "Remnant"

### ISSUE THREAD

**Issue by heshtur** [Razzmatazzz/ValheimSaveShield#7]
Mousing over the "Save Folder" and "FTP Import" text boxes brings up a tooltip about Remnant save locations instead of Valheim.

![image](https://user-images.githubusercontent.com/10300101/108102187-13a79d80-703d-11eb-9db1-9d196c67c6aa.png)

**Comment by heshtur** [comment]
Lines 82 and 84 in the file MainWindow.xaml if I'm not mistaken, to save you time searching.

**Comment by Razzmatazzz** [comment]
Thanks. That's what I get for reusing UI and code. Will be fixed in next release.
