### ISSUE TITLE
Suggestion: Backup from multiple save folders

### ISSUE THREAD

**Issue by Blixtmen** [Razzmatazzz/ValheimSaveShield#8]
Would be useful when hosting a dedicated server on the same computer which you play on, that uses a different savedir for the world!

**Comment by Razzmatazzz** [comment]
Why not just use the same folder for the dedicated server as everything else?

**Comment by Blixtmen** [comment]
Just prefer having the world folder together with the server, more convenient for keeping it portable / moving to other PCs

**Comment by Razzmatazzz** [comment]
I find it more convenient to keep all the saves in the same place so I don't have to build extra features. :)

**Comment by Blixtmen** [comment]
Understand, it's only a suggestion! =]
(Maybe a better description is, choosing a save location for worlds and one for characters - defaults to appdata)

**Comment by Razzmatazzz** [comment]
Setting separate save folders for worlds vs. characters means it wouldn't automatically back up the world when someone is playing singleplayer. :/

**Comment by timdonovanuk** [comment]
And what if you don't have a server on the same machine? I run a dedicated server on..a server..so my characters live locally but the words are on a network share, e.g.:

- C:\Users\<username>\AppData\LocalLow\IronGate\Valheim 
- \\server\valheim\worlds

Are you suggesting I point the game at my dedicated server folder to save my character?

**Comment by Razzmatazzz** [comment]
If your dedicated server is running windows, just run this app separately on the dedicated server. If not, give yourself ftp access to the save folder on the dedicated server and use that feature.

**Comment by PolarKC** [comment]
This would be incredibly useful. Not _necessary_, but incredibly useful.

**Comment by Razzmatazzz** [comment]
Can someone with this use case test the attached to make sure it works as intended?
[vss-test-2020-02-25.zip](https://github.com/Razzmatazzz/ValheimSaveShield/files/6045471/vss-test-2020-02-25.zip)

**Comment by Razzmatazzz** [comment]
Ok, this version should be ready for testing.
[vss-2021-02-25 02.zip](https://github.com/Razzmatazzz/ValheimSaveShield/files/6045993/vss-2021-02-25.02.zip)

**Comment by Blixtmen** [comment]
Glad you changed your mind, thanks for implementing the feature! =)

**Comment by Razzmatazzz** [comment]
Once I realized that someone might want to run multiple servers with different savedirs for admin/banned/permitted lists, I didn't really have much of a choice!
